name: jira Exporter Workflow for Port

on:
  push:
    branches:
      - main
  # You can uncomment this to schedule the job hourly:
  # schedule:
  #   - cron: '0 */1 * * *'

jobs:
  run-integration:
    runs-on: ubuntu-latest
    timeout-minutes: 30  # Corrected indentation

    steps:
      - name: Run jira Integration
        uses: port-labs/ocean-sail@v1
        with:
          type: jira
          port_client_id: ${{ secrets.PORT_CLIENT_ID }}
          port_client_secret: ${{ secrets.PORT_CLIENT_SECRET }}
          port_base_url: "https://api.port.io"
          config: |
            jira_host: "https://elokadevops.atlassian.net"
            atlassian_user_email: ${{ secrets.atlassianUserEmail }}
            atlassian_user_token: ${{ secrets.atlassianUserToken }}
